include("../src/PAKNZEJulia.jl")
using .PAKNZEJulia
include("model_architecture.jl")
include("summary_tables.jl")
include("generation_mix.jl")
include("power_sector_emissions.jl")
include("power_sector_fuel_imports.jl")
include("hydrogen_capacity.jl")
include("climate_feedback_impact.jl")
include("provincial_outputs.jl")
include("validation.jl")
run_model_architecture(); run_summary_tables(); run_generation_mix(); run_power_sector_emissions(); run_power_sector_fuel_imports(); run_hydrogen_capacity(); run_climate_feedback_impact(); run_provincial_outputs(); run_validation(); println("Post-processing complete")
