include("sankey_2024.jl")
include("generation_mix.jl")
include("decarbonisation_trajectory.jl")
include("import_dependency.jl")
include("nze_emissions_decomposition.jl")
include("climate_feedback_impact.jl")
include("provincial_outputs.jl")
include("validation.jl")
run_sankey_2024(); run_generation_mix(); run_decarbonisation_trajectory(); run_import_dependency(); run_nze_emissions_decomposition(); run_climate_feedback_impact(); run_provincial_outputs(); run_validation(); println("Post-processing complete")
